version: "3.9"
services:
  postgres-authman:
    image: postgres:9.6-alpine
    restart: unless-stopped
    hostname: kratos-database-authman
    container_name: kratos-database-authman
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./postgres-dump:/dump
      - postgres-data-kratos:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"

  kratos-migrate-authman:
    image: oryd/kratos:v1.1.0
    hostname: kratos-migrate-authman
    container_name: kratos-migrate-authman
    depends_on:
      - postgres-authman
    environment:
      - DSN=postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:5432/${DB_NAME}?sslmode=disable&max_conns=20&max_idle_conns=4
    volumes:
      - ./kratos:/etc/config/kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    restart: "no"

  kratos-authman:
    image: oryd/kratos:v1.1.0
    hostname: kratos-authman
    container_name: kratos-authman
    depends_on:
      - kratos-migrate-authman
    environment:
      - DSN=postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:5432/${DB_NAME}?sslmode=disable&max_conns=20&max_idle_conns=4
    ports:
      - ${KRATOS_EXPOSE_PORT}:4433
      - ${KRATOS_ADMIN_EXPOSE_PORT}:4434
    volumes:
      - ./kratos:/etc/config/kratos
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier --sqa-opt-out
    restart: unless-stopped

  kratos-selfservice-ui-node-authman:
    image: oryd/kratos-selfservice-ui-node:v1.0.0
    hostname: kratos-selfservice-ui-node-authman
    container_name: kratos-selfservice-ui-node-authman
    depends_on:
      - kratos-migrate-authman
    environment:
      - KRATOS_PUBLIC_URL=http://kratos-authman:4433/
      - KRATOS_BROWSER_URL=http://127.0.0.1:${KRATOS_EXPOSE_PORT}/
    ports:
      - ${KRATOS_UI_EXPOSE_PORT}:3000
    restart: unless-stopped

volumes:
  postgres-data-kratos:
  kratos:

networks:
  default:
    name: kratos-authman-net